on:
  push:
    branches:
      - main

permissions:
  deployments: write
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create
        run: |
          echo 'Creating release tarball...' 
          find ./src -name "*.py" | sed 's/\.\/src\///' | tar -caf greet.tar.gz -C src -T -
          echo 'Inspecting the tarball:'
          tar -tf greet.tar.gz
      - name: Upload
        run: gh release create v0.0.2 greet.tar.gz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
